version: "3.7"
services:
  flight:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: flights
    volumes:
      - ./:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017